import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const sourcePath = resolve(root, "vendor/cn/packages/cn/src/tables.generated.ts")
const source = readFileSync(sourcePath, "utf8")

function capture(re, label) {
  const match = source.match(re)
  if (!match) throw new Error(`cannot extract ${label}`)
  return match[1]
}

function jsString(name, expression = `${name} = `) {
  const raw = capture(
    new RegExp(`${expression.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}((?:"(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*'))`),
    name
  )
  return JSON.stringify(Function(`return (${raw})`)())
}

const uFields = ["edgeStart", "labelStart", "nodeGroup", "vlistPat", "vlistOps", "vlistRef"]
const dzFields = ["vlistGroup", "AA", "AG", "AS", "adjGid", "adjTgt"]
const values = {}

for (const name of uFields) {
  const m = source.match(new RegExp(`const ${name} = (PS\\()?U\\(((?:"(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*'))(?:, (\\d+))?\\)\\)?`))
  if (!m) throw new Error(`cannot extract ${name}`)
  values[name] = {
    text: JSON.stringify(Function(`return (${m[2]})`)()),
    offset: Number(m[3] ?? 0),
    prefix: m[1] ? "prefix(" : "decode(",
  }
}
for (const name of dzFields) {
  const raw = capture(new RegExp(`const ${name} = DZ\\(((?:"(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*'))\\)`), name)
  values[name] = JSON.stringify(Function(`return (${raw})`)())
}

const groupCount = Number(capture(/const GROUP_COUNT = (\d+)/, "GROUP_COUNT"))
const labelText = jsString("labelText")
const sets = jsString("SETS")
const adjStartRaw = capture(/const adjStart = PS\(U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)\)/, "adjStart")
const adjStart = JSON.stringify(Function(`return (${adjStartRaw})`)())
const patGidRaw = capture(/const patGid = U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "patGid")
const patGid = JSON.stringify(Function(`return (${patGidRaw})`)())
const patTgtRaw = capture(/const patTgt = U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "patTgt")
const patTgt = JSON.stringify(Function(`return (${patTgtRaw})`)())
const postfixRaw = capture(/const postfixLookupGroups = U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "postfixLookupGroups")
const postfix = JSON.stringify(Function(`return (${postfixRaw})`)())
const orderSensitive = jsString("orderSensitiveModifiers")

const lil = `// GENERATED from shadcn-ui/cn ${capture(/GENERATED by ([^\n]+)/, "generator provenance")}\n// Source pin: c003999e2456266c1b0e9d8ed4e2ca855d5eb38f\n// Module-level tables: each exported binding is one of upstream's closure constants, so the\n// engine reads it as a single context-slot load (finer 048), never through a handle.\n\n+int PACK_BASE = 48;\n+\n+Int32Array decode(string source, int offset = 0) {\n+  Int32Array out = new Int32Array(source.length);\n+  int index = 0;\n+  while (index < source.length) {\n+    out[index] = source.charCodeAt(index) - PACK_BASE - offset;\n+    index = index + 1;\n+  }\n+  return out;\n+}\n+\n+Int32Array prefix(Int32Array counts) {\n+  Int32Array out = new Int32Array(counts.length + 1);\n+  int index = 0;\n+  while (index < counts.length) {\n+    out[index + 1] = out[index] + counts[index];\n+    index = index + 1;\n+  }\n+  return out;\n+}\n+\n+Int32Array deltaZigzag(string source) {\n+  Int32Array out = new Int32Array(source.length);\n+  int accumulator = 0;\n+  int index = 0;\n+  while (index < source.length) {\n+    int zigzag = source.charCodeAt(index) - PACK_BASE;\n+    accumulator = accumulator + ((zigzag >>> 1) ^ (0 - (zigzag & 1)));\n+    out[index] = accumulator;\n+    index = index + 1;\n+  }\n+  return out;\n+}\n+\n+// pre-order tree: targets derived from edge counts via subtree sizes\n+Int32Array buildEdgeTarget(Int32Array starts) {\n+  int nodeCount = starts.length - 1;\n+  Int32Array sizes = new Int32Array(nodeCount);\n+  int nodeIndex = nodeCount - 1;\n+  while (nodeIndex >= 0) {\n+    int size = 1;\n+    int child = nodeIndex + 1;\n+    int edge = starts[nodeIndex];\n+    while (edge < starts[nodeIndex + 1]) {\n+      size = size + sizes[child];\n+      child = child + sizes[child];\n+      edge = edge + 1;\n+    }\n+    sizes[nodeIndex] = size;\n+    nodeIndex = nodeIndex - 1;\n+  }\n+  Int32Array targets = new Int32Array(starts[nodeCount]);\n+  int targetEdge = 0;\n+  nodeIndex = 0;\n+  while (nodeIndex < nodeCount) {\n+    int child = nodeIndex + 1;\n+    int edge = starts[nodeIndex];\n+    while (edge < starts[nodeIndex + 1]) {\n+      targets[targetEdge] = child;\n+      targetEdge = targetEdge + 1;\n+      child = child + sizes[child];\n+      edge = edge + 1;\n+    }\n+    nodeIndex = nodeIndex + 1;\n+  }\n+  return targets;\n+}\n+\n+Int32Array buildNodeVlist(int nodeCount, string anchorSource, string listSource) {\n+  Int32Array lists = new Int32Array(nodeCount);\n+  lists.fill(-1);\n+  Int32Array anchors = deltaZigzag(anchorSource);\n+  Int32Array values = deltaZigzag(listSource);\n+  int sparseIndex = 0;\n+  while (sparseIndex < anchors.length) {\n+    lists[anchors[sparseIndex]] = values[sparseIndex];\n+    sparseIndex = sparseIndex + 1;\n+  }\n+  return lists;\n+}\n+\n+export int groupCount = ${groupCount};\n+export Int32Array edgeStart = ${values.edgeStart.prefix}decode(${values.edgeStart.text}, ${values.edgeStart.offset}));\n+export Int32Array labelStart = ${values.labelStart.prefix}decode(${values.labelStart.text}, ${values.labelStart.offset}));\n+export string labelText = ${labelText};\n+export Int32Array edgeTarget = buildEdgeTarget(edgeStart);\n+export Int32Array nodeGroup = decode(${values.nodeGroup.text}, ${values.nodeGroup.offset});\n+export Int32Array nodeVlist = buildNodeVlist(318, ${JSON.stringify(Function(`return (${capture(/const A = DZ\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "nodeVlist anchors")})`)())}, ${JSON.stringify(Function(`return (${capture(/const V = DZ\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "nodeVlist lists")})`)())});\n+export Int32Array vlistPat = ${values.vlistPat.prefix}decode(${values.vlistPat.text}, ${values.vlistPat.offset}));\n+export Int32Array vlistOps = decode(${values.vlistOps.text}, ${values.vlistOps.offset});\n+export Int32Array vlistRef = decode(${values.vlistRef.text}, ${values.vlistRef.offset});\n+export Int32Array vlistGroup = deltaZigzag(${values.vlistGroup});\n+\n+// lifted literal tails: (anchor node, tail) -> group, tails deduplicated into one text pool\n+export Int32Array litAnchor = new Int32Array(974);\n+export Int32Array litGroup = new Int32Array(974);\n+export Int32Array litPool = new Int32Array(974);\n+export Int32Array poolOffsets = new Int32Array(1008);\n+\n+string buildLiteralPool() {\n+  string[] setBlobs = ${sets}.split("|");\n+  string[][] sets = [];\n+  int setIndex = 0;\n+  while (setIndex < setBlobs.length) {\n+    sets.push(setBlobs[setIndex].split(" "));\n+    setIndex = setIndex + 1;\n+  }\n+  Int32Array literalAnchors = deltaZigzag(${values.AA});\n+  Int32Array literalGroups = deltaZigzag(${values.AG});\n+  Int32Array literalSets = deltaZigzag(${values.AS});\n+  string text = "";\n+  Map<string, int> tailRef = new Map<string, int>();\n+  int nextRef = 0;\n+  int entry = 0;\n+  int row = 0;\n+  while (row < literalAnchors.length) {\n+    string[] tails = sets[literalSets[row]];\n+    int tailIndex = 0;\n+    while (tailIndex < tails.length) {\n+      string tail = tails[tailIndex];\n+      int? maybeRef = tailRef.get(tail);\n+      int reference = 0;\n+      if (maybeRef == null) {\n+        reference = nextRef;\n+        nextRef = nextRef + 1;\n+        tailRef.set(tail, reference);\n+        poolOffsets[reference * 2] = text.length;\n+        poolOffsets[reference * 2 + 1] = tail.length;\n+        text = text + tail;\n+      } else {\n+        reference = maybeRef;\n+      }\n+      litAnchor[entry] = literalAnchors[row];\n+      litGroup[entry] = literalGroups[row];\n+      litPool[entry] = reference;\n+      entry = entry + 1;\n+      tailIndex = tailIndex + 1;\n+    }\n+    row = row + 1;\n+  }\n+  return text;\n+}\n+export string poolText = buildLiteralPool();\n+\n+// conflict adjacency (the engine builds its claim rows at init)\n+export Int32Array adjGid = deltaZigzag(${values.adjGid});\n+export Int32Array adjStart = prefix(decode(${adjStart}));\n+export Int32Array adjTgt = deltaZigzag(${values.adjTgt});\n+export Int32Array patGid = decode(${patGid});\n+export Int32Array patTgt = decode(${patTgt});\n+export Int32Array postfixLookupGroups = decode(${postfix});\n+export string orderSensitiveModifiers = ${orderSensitive};\n+export string prefixValue = "";\n+`

mkdirSync(resolve(root, "src"), { recursive: true })
writeFileSync(resolve(root, "src/tables.lil"), lil.replace(/^\+/gm, ""))
console.log("generated src/tables.lil from pinned upstream tables")
