import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const sourcePath = resolve(root, "vendor/cn/packages/cn/src/tables.generated.ts")
const source = readFileSync(sourcePath, "utf8")

function capture(re, label) {
  const match = source.match(re)
  if (!match) throw new Error(`cannot extract ${label}`)
  return match[1]
}

function jsString(name, expression = `${name} = `) {
  const raw = capture(
    new RegExp(`${expression.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}((?:"(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*'))`),
    name
  )
  return JSON.stringify(Function(`return (${raw})`)())
}

const uFields = ["edgeStart", "labelStart", "nodeGroup", "vlistPat", "vlistOps", "vlistRef"]
const dzFields = ["vlistGroup", "AA", "AG", "AS", "adjGid", "adjTgt"]
const values = {}

for (const name of uFields) {
  const m = source.match(new RegExp(`const ${name} = (PS\\()?U\\(((?:"(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*'))(?:, (\\d+))?\\)\\)?`))
  if (!m) throw new Error(`cannot extract ${name}`)
  values[name] = {
    text: JSON.stringify(Function(`return (${m[2]})`)()),
    offset: Number(m[3] ?? 0),
    prefix: m[1] ? "prefix(" : "decode(",
  }
}
for (const name of dzFields) {
  const raw = capture(new RegExp(`const ${name} = DZ\\(((?:"(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*'))\\)`), name)
  values[name] = JSON.stringify(Function(`return (${raw})`)())
}

const groupCount = Number(capture(/const GROUP_COUNT = (\d+)/, "GROUP_COUNT"))
const labelText = jsString("labelText")
const sets = jsString("SETS")
const adjStartRaw = capture(/const adjStart = PS\(U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)\)/, "adjStart")
const adjStart = JSON.stringify(Function(`return (${adjStartRaw})`)())
const patGidRaw = capture(/const patGid = U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "patGid")
const patGid = JSON.stringify(Function(`return (${patGidRaw})`)())
const patTgtRaw = capture(/const patTgt = U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "patTgt")
const patTgt = JSON.stringify(Function(`return (${patTgtRaw})`)())
const postfixRaw = capture(/const postfixLookupGroups = U\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "postfixLookupGroups")
const postfix = JSON.stringify(Function(`return (${postfixRaw})`)())
const orderSensitive = jsString("orderSensitiveModifiers")

const lil = `// GENERATED from shadcn-ui/cn ${capture(/GENERATED by ([^\n]+)/, "generator provenance")}\n// Source pin: c003999e2456266c1b0e9d8ed4e2ca855d5eb38f\n\n+int PACK_BASE = 48;\n+\n+Int32Array decode(string source, int offset = 0) {\n+  Int32Array out = new Int32Array(source.length);\n+  int index = 0;\n+  while (index < source.length) {\n+    out[index] = source.charCodeAt(index) - PACK_BASE - offset;\n+    index = index + 1;\n+  }\n+  return out;\n+}\n+\n+Int32Array prefix(Int32Array counts) {\n+  Int32Array out = new Int32Array(counts.length + 1);\n+  int index = 0;\n+  while (index < counts.length) {\n+    out[index + 1] = out[index] + counts[index];\n+    index = index + 1;\n+  }\n+  return out;\n+}\n+\n+Int32Array deltaZigzag(string source) {\n+  Int32Array out = new Int32Array(source.length);\n+  int accumulator = 0;\n+  int index = 0;\n+  while (index < source.length) {\n+    int zigzag = source.charCodeAt(index) - PACK_BASE;\n+    accumulator = accumulator + ((zigzag >>> 1) ^ (0 - (zigzag & 1)));\n+    out[index] = accumulator;\n+    index = index + 1;\n+  }\n+  return out;\n+}\n+\n+export class Tables {\n+  int groupCount;\n+  Int32Array edgeStart;\n+  Int32Array labelStart;\n+  string labelText;\n+  Int32Array edgeTarget;\n+  Int32Array nodeGroup;\n+  Int32Array nodeVlist;\n+  Int32Array vlistPat;\n+  Int32Array vlistOps;\n+  Int32Array vlistRef;\n+  Int32Array vlistGroup;\n+  Int32Array litAnchor;\n+  Int32Array litGroup;\n+  Int32Array litPool;\n+  Int32Array poolOffsets;\n+  string poolText;\n+  Int32Array adjGid;\n+  Int32Array adjStart;\n+  Int32Array adjTgt;\n+  Int32Array patGid;\n+  Int32Array patTgt;\n+  Int32Array postfixLookupGroups;\n+  string orderSensitiveModifiers;\n+  string prefixValue;\n+\n+  init() {\n+    this.groupCount = ${groupCount};\n+    this.edgeStart = ${values.edgeStart.prefix}decode(${values.edgeStart.text}, ${values.edgeStart.offset}));\n+    this.labelStart = ${values.labelStart.prefix}decode(${values.labelStart.text}, ${values.labelStart.offset}));\n+    this.labelText = ${labelText};\n+    int nodeCount = this.edgeStart.length - 1;\n+    Int32Array sizes = new Int32Array(nodeCount);\n+    int nodeIndex = nodeCount - 1;\n+    while (nodeIndex >= 0) {\n+      int size = 1;\n+      int child = nodeIndex + 1;\n+      int edge = this.edgeStart[nodeIndex];\n+      while (edge < this.edgeStart[nodeIndex + 1]) {\n+        size = size + sizes[child];\n+        child = child + sizes[child];\n+        edge = edge + 1;\n+      }\n+      sizes[nodeIndex] = size;\n+      nodeIndex = nodeIndex - 1;\n+    }\n+    this.edgeTarget = new Int32Array(this.edgeStart[nodeCount]);\n+    int targetEdge = 0;\n+    nodeIndex = 0;\n+    while (nodeIndex < nodeCount) {\n+      int child = nodeIndex + 1;\n+      int edge = this.edgeStart[nodeIndex];\n+      while (edge < this.edgeStart[nodeIndex + 1]) {\n+        this.edgeTarget[targetEdge] = child;\n+        targetEdge = targetEdge + 1;\n+        child = child + sizes[child];\n+        edge = edge + 1;\n+      }\n+      nodeIndex = nodeIndex + 1;\n+    }\n+    this.nodeGroup = decode(${values.nodeGroup.text}, ${values.nodeGroup.offset});\n+    this.vlistPat = ${values.vlistPat.prefix}decode(${values.vlistPat.text}, ${values.vlistPat.offset}));\n+    this.vlistOps = decode(${values.vlistOps.text}, ${values.vlistOps.offset});\n+    this.vlistRef = decode(${values.vlistRef.text}, ${values.vlistRef.offset});\n+    this.vlistGroup = deltaZigzag(${values.vlistGroup});\n+    this.nodeVlist = new Int32Array(318);\n+    this.nodeVlist.fill(-1);\n+    Int32Array anchors = deltaZigzag(${JSON.stringify(Function(`return (${capture(/const A = DZ\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "nodeVlist anchors")})`)())});\n+    Int32Array lists = deltaZigzag(${JSON.stringify(Function(`return (${capture(/const V = DZ\(((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'))\)/, "nodeVlist lists")})`)())});\n+    int sparseIndex = 0;\n+    while (sparseIndex < anchors.length) {\n+      this.nodeVlist[anchors[sparseIndex]] = lists[sparseIndex];\n+      sparseIndex = sparseIndex + 1;\n+    }\n+    string[] setBlobs = ${sets}.split("|");\n+    string[][] sets = [];\n+    int setIndex = 0;\n+    while (setIndex < setBlobs.length) {\n+      sets.push(setBlobs[setIndex].split(" "));\n+      setIndex = setIndex + 1;\n+    }\n+    Int32Array literalAnchors = deltaZigzag(${values.AA});\n+    Int32Array literalGroups = deltaZigzag(${values.AG});\n+    Int32Array literalSets = deltaZigzag(${values.AS});\n+    this.litAnchor = new Int32Array(974);\n+    this.litGroup = new Int32Array(974);\n+    this.litPool = new Int32Array(974);\n+    this.poolOffsets = new Int32Array(1008);\n+    this.poolText = "";\n+    Map<string, int> tailRef = new Map<string, int>();\n+    int nextRef = 0;\n+    int entry = 0;\n+    int row = 0;\n+    while (row < literalAnchors.length) {\n+      string[] tails = sets[literalSets[row]];\n+      int tailIndex = 0;\n+      while (tailIndex < tails.length) {\n+        string tail = tails[tailIndex];\n+        int? maybeRef = tailRef.get(tail);\n+        int reference = 0;\n+        if (maybeRef == null) {\n+          reference = nextRef;\n+          nextRef = nextRef + 1;\n+          tailRef.set(tail, reference);\n+          this.poolOffsets[reference * 2] = this.poolText.length;\n+          this.poolOffsets[reference * 2 + 1] = tail.length;\n+          this.poolText = this.poolText + tail;\n+        } else {\n+          reference = maybeRef;\n+        }\n+        this.litAnchor[entry] = literalAnchors[row];\n+        this.litGroup[entry] = literalGroups[row];\n+        this.litPool[entry] = reference;\n+        entry = entry + 1;\n+        tailIndex = tailIndex + 1;\n+      }\n+      row = row + 1;\n+    }\n+    this.adjGid = deltaZigzag(${values.adjGid});\n+    this.adjStart = prefix(decode(${adjStart}));\n+    this.adjTgt = deltaZigzag(${values.adjTgt});\n+    this.patGid = decode(${patGid});\n+    this.patTgt = decode(${patTgt});\n+    this.postfixLookupGroups = decode(${postfix});\n+    this.orderSensitiveModifiers = ${orderSensitive};\n+    this.prefixValue = "";\n+  }\n+}\n+\n+export Tables defaultTables = new Tables();\n+`

mkdirSync(resolve(root, "src"), { recursive: true })
writeFileSync(resolve(root, "src/tables.lil"), lil.replace(/^\+/gm, ""))
console.log("generated src/tables.lil from pinned upstream tables")
